name: Linter

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches:
      - master
      - devel
  push:
    branches:
      - master
      - devel

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  Lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: npm install
      - name: Linter
        run: npm run lint
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
